### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by interaminense** [NevinhaJS/nevinha-js#54]
Hey @clovisdasilvaneto,
Do you think to add unit tests?

**Comment by clovisdasilvaneto** [comment]
@interaminense  Yes! I just don't had time yet, because I'm finishing nevinha-redux module. I already finished the example using redux with providers and connect functions in this [example](https://github.com/NevinhaJS/nevinha-js-examples/tree/master/redux-example). Now I'm refactoring this example to put all in order... The example files in the nevinha-redux-example and the nevinha-redux files in the nevinha-redux repository.

I've created the task to add unit test in the github projects, but I don't know if you can see: https://github.com/NevinhaJS/nevinha-js/projects/1

**Comment by clovisdasilvaneto** [comment]
Awesom 😃!!!

We could use Jest, what do you think?

**Comment by interaminense** [comment]
The jest sounds good!!

**Comment by interaminense** [comment]
Hey @clovisdasilvaneto, I sent the PR with jest here https://github.com/nevinhajs/nevinha-js/pull/62

**Comment by clovisdasilvaneto** [comment]
Good job!! 👏🏻👏🏻👏🏻👏🏻 

Tnks
